INSERT INTO GlobalCategories (Name, ParentId)
VALUES
    ('Food & Drink', NULL),
    ('Shopping', NULL),
    ('Home', NULL),
    ('Transport', NULL),
    ('Vehicles', NULL),
    ('Entertainment', NULL),
    ('Education', NULL);

INSERT INTO GlobalCategories (Name, ParentId)
VALUES
    ('Bar', (SELECT Id FROM GlobalCategories WHERE Name = 'Food & Drink')),
    ('Coffee', (SELECT Id FROM GlobalCategories WHERE Name = 'Food & Drink')),
    ('Restaurant', (SELECT Id FROM GlobalCategories WHERE Name = 'Food & Drink')),
    ('Supermarket', (SELECT Id FROM GlobalCategories WHERE Name = 'Food & Drink')),
    ('Children', (SELECT Id FROM GlobalCategories WHERE Name = 'Shopping')),
    ('House', (SELECT Id FROM GlobalCategories WHERE Name = 'Shopping')),
    ('Shoes', (SELECT Id FROM GlobalCategories WHERE Name = 'Shopping')),
    ('Clothes', (SELECT Id FROM GlobalCategories WHERE Name = 'Shopping')),
    ('Gifts', (SELECT Id FROM GlobalCategories WHERE Name = 'Shopping')),
    ('Medicine', (SELECT Id FROM GlobalCategories WHERE Name = 'Shopping')),
    ('Electronics', (SELECT Id FROM GlobalCategories WHERE Name = 'Shopping')),
    ('Accessories', (SELECT Id FROM GlobalCategories WHERE Name = 'Shopping')),
    ('Mortgages', (SELECT Id FROM GlobalCategories WHERE Name = 'Home')),
    ('Maintenance', (SELECT Id FROM GlobalCategories WHERE Name = 'Home')),
    ('Rent', (SELECT Id FROM GlobalCategories WHERE Name = 'Home')),
    ('Property Insurance', (SELECT Id FROM GlobalCategories WHERE Name = 'Home')),
    ('Services', (SELECT Id FROM GlobalCategories WHERE Name = 'Home')),
    ('Travel', (SELECT Id FROM GlobalCategories WHERE Name = 'Transport')),
    ('Taxi', (SELECT Id FROM GlobalCategories WHERE Name = 'Transport')),
    ('Public Transport', (SELECT Id FROM GlobalCategories WHERE Name = 'Transport')),
    ('Rental', (SELECT Id FROM GlobalCategories WHERE Name = 'Vehicles')),
    ('Fuel', (SELECT Id FROM GlobalCategories WHERE Name = 'Vehicles')),
    ('Parking', (SELECT Id FROM GlobalCategories WHERE Name = 'Vehicles')),
    ('Maintenance', (SELECT Id FROM GlobalCategories WHERE Name = 'Vehicles')),
    ('Insurance', (SELECT Id FROM GlobalCategories WHERE Name = 'Vehicles')),
    ('Special Events', (SELECT Id FROM GlobalCategories WHERE Name = 'Entertainment')),
    ('TV Streaming', (SELECT Id FROM GlobalCategories WHERE Name = 'Entertainment')),
    ('Alcohol', (SELECT Id FROM GlobalCategories WHERE Name = 'Entertainment')),
    ('Fitness', (SELECT Id FROM GlobalCategories WHERE Name = 'Entertainment')),
    ('Sport', (SELECT Id FROM GlobalCategories WHERE Name = 'Entertainment')),
    ('Books', (SELECT Id FROM GlobalCategories WHERE Name = 'Entertainment')),
    ('Subscriptions', (SELECT Id FROM GlobalCategories WHERE Name = 'Entertainment')),
    ('Vacations', (SELECT Id FROM GlobalCategories WHERE Name = 'Entertainment')),
    ('Kindergarten', (SELECT Id FROM GlobalCategories WHERE Name = 'Education')),
    ('Elementary School', (SELECT Id FROM GlobalCategories WHERE Name = 'Education')),
    ('Middle School', (SELECT Id FROM GlobalCategories WHERE Name = 'Education')),
    ('High School', (SELECT Id FROM GlobalCategories WHERE Name = 'Education')),
    ('Undergraduate', (SELECT Id FROM GlobalCategories WHERE Name = 'Education')),
    ('Graduate', (SELECT Id FROM GlobalCategories WHERE Name = 'Education')),
    ('Online Courses', (SELECT Id FROM GlobalCategories WHERE Name = 'Education'));