INSERT INTO GlobalCategories (Id, Name, ParentId)
VALUES
    (1, 'Food & Drink', NULL),
    (2, 'Shoping', NULL),
    (3, 'Home', NULL),
    (4, 'Transport', NULL),
    (5, 'Vehicles', NULL),
    (6, 'Entretaiment', NULL),
    (7, 'Education', NULL),
    ('Bar', 1),
    ('Coffe', 1),
    ('Restaurant', 1),
    ('Supermarket', 1),
    ('Children', 2),
    ('House', 2),
    ('Shoes', 2),
    ('Clothes', 2),
    ('Gifts', 2),
    ('Medicine', 2),
    ('Electronic', 2),
    ('Accesories', 2),
    ('Mortgages', 3),
    ('Mantainance', 3),
    ('Rent', 3),
    ('Property Insurance', 3),
    ('Services', 3),
    ('Travel', 4),
    ('Taxi', 4),
    ('Public Transport', 4),
    ('Rental', 5),
    ('Fuel', 5),
    ('Parking', 5),
    ('Mantainance', 5),
    ('Insurance', 5),
    ('Special Events', 6),
    ('TV Streaming', 6),
    ('Alcohol', 6),
    ('Fitness', 6),
    ('Sport', 6),
    ('Books', 6),
    ('Suscriptions', 6),
    ('Vacations', 6),
    ('Kindergarten', 7),
    ('Elementary School', 7),
    ('Middle School', 7),
    ('High School', 7),
    ('Undergraduate', 7),
    ('Graduate', 7),
    ('Online Courses', 7);