INSERT INTO Categories (Name, ParentId, IsGlobal, UserId)
VALUES
    ('Food & Drink', NULL, TRUE, NULL),
    ('Shopping', NULL, TRUE, NULL),
    ('Home', NULL, TRUE, NULL),
    ('Transport', NULL, TRUE, NULL),
    ('Vehicles', NULL, TRUE, NULL),
    ('Entertainment', NULL, TRUE, NULL),
    ('Education', NULL, TRUE, NULL);

INSERT INTO Categories (Name, ParentId, IsGlobal, UserId)
VALUES
    ('Bar', (SELECT Id FROM Categories WHERE Name = 'Food & Drink'), TRUE, NULL),
    ('Coffee', (SELECT Id FROM Categories WHERE Name = 'Food & Drink'), TRUE, NULL),
    ('Restaurant', (SELECT Id FROM Categories WHERE Name = 'Food & Drink'), TRUE, NULL),
    ('Supermarket', (SELECT Id FROM Categories WHERE Name = 'Food & Drink'), TRUE, NULL),
    ('Children', (SELECT Id FROM Categories WHERE Name = 'Shopping'), TRUE, NULL),
    ('House', (SELECT Id FROM Categories WHERE Name = 'Shopping'), TRUE, NULL),
    ('Shoes', (SELECT Id FROM Categories WHERE Name = 'Shopping'), TRUE, NULL),
    ('Clothes', (SELECT Id FROM Categories WHERE Name = 'Shopping'), TRUE, NULL),
    ('Gifts', (SELECT Id FROM Categories WHERE Name = 'Shopping'), TRUE, NULL),
    ('Medicine', (SELECT Id FROM Categories WHERE Name = 'Shopping'), TRUE, NULL),
    ('Electronics', (SELECT Id FROM Categories WHERE Name = 'Shopping'), TRUE, NULL),
    ('Accessories', (SELECT Id FROM Categories WHERE Name = 'Shopping'), TRUE, NULL),
    ('Mortgages', (SELECT Id FROM Categories WHERE Name = 'Home'), TRUE, NULL),
    ('Maintenance', (SELECT Id FROM Categories WHERE Name = 'Home'), TRUE, NULL),
    ('Rent', (SELECT Id FROM Categories WHERE Name = 'Home'), TRUE, NULL),
    ('Property Insurance', (SELECT Id FROM Categories WHERE Name = 'Home'), TRUE, NULL),
    ('Services', (SELECT Id FROM Categories WHERE Name = 'Home'), TRUE, NULL),
    ('Travel', (SELECT Id FROM Categories WHERE Name = 'Transport'), TRUE, NULL),
    ('Taxi', (SELECT Id FROM Categories WHERE Name = 'Transport'), TRUE, NULL),
    ('Public Transport', (SELECT Id FROM Categories WHERE Name = 'Transport'), TRUE, NULL),
    ('Rental', (SELECT Id FROM Categories WHERE Name = 'Vehicles'), TRUE, NULL),
    ('Fuel', (SELECT Id FROM Categories WHERE Name = 'Vehicles'), TRUE, NULL),
    ('Parking', (SELECT Id FROM Categories WHERE Name = 'Vehicles'), TRUE, NULL),
    ('Maintenance', (SELECT Id FROM Categories WHERE Name = 'Vehicles'), TRUE, NULL),
    ('Insurance', (SELECT Id FROM Categories WHERE Name = 'Vehicles'), TRUE, NULL),
    ('Special Events', (SELECT Id FROM Categories WHERE Name = 'Entertainment'), TRUE, NULL),
    ('TV Streaming', (SELECT Id FROM Categories WHERE Name = 'Entertainment'), TRUE, NULL),
    ('Alcohol', (SELECT Id FROM Categories WHERE Name = 'Entertainment'), TRUE, NULL),
    ('Fitness', (SELECT Id FROM Categories WHERE Name = 'Entertainment'), TRUE, NULL),
    ('Sport', (SELECT Id FROM Categories WHERE Name = 'Entertainment'), TRUE, NULL),
    ('Books', (SELECT Id FROM Categories WHERE Name = 'Entertainment'), TRUE, NULL),
    ('Subscriptions', (SELECT Id FROM Categories WHERE Name = 'Entertainment'), TRUE, NULL),
    ('Vacations', (SELECT Id FROM Categories WHERE Name = 'Entertainment'), TRUE, NULL),
    ('Kindergarten', (SELECT Id FROM Categories WHERE Name = 'Education'), TRUE, NULL),
    ('Elementary School', (SELECT Id FROM Categories WHERE Name = 'Education'), TRUE, NULL),
    ('Middle School', (SELECT Id FROM Categories WHERE Name = 'Education'), TRUE, NULL),
    ('High School', (SELECT Id FROM Categories WHERE Name = 'Education'), TRUE, NULL),
    ('Undergraduate', (SELECT Id FROM Categories WHERE Name = 'Education'), TRUE, NULL),
    ('Graduate', (SELECT Id FROM Categories WHERE Name = 'Education'), TRUE, NULL),
    ('Online Courses', (SELECT Id FROM Categories WHERE Name = 'Education'), TRUE, NULL);